/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppPasswordRouteImport } from './routes/app-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGenqrRouteImport } from './routes/api/public/genqr'
import { Route as ApiPublicCheckRouteImport } from './routes/api/public/check'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPasswordRoute = AppPasswordRouteImport.update({
  id: '/app-password',
  path: '/app-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenqrRoute = ApiPublicGenqrRouteImport.update({
  id: '/api/public/genqr',
  path: '/api/public/genqr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckRoute = ApiPublicCheckRouteImport.update({
  id: '/api/public/check',
  path: '/api/public/check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app-password': typeof AppPasswordRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/genqr': typeof ApiPublicGenqrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app-password': typeof AppPasswordRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/genqr': typeof ApiPublicGenqrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app-password': typeof AppPasswordRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/genqr': typeof ApiPublicGenqrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app-password'
    | '/dashboard'
    | '/docs'
    | '/keys'
    | '/login'
    | '/register'
    | '/api/public/check'
    | '/api/public/genqr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/app-password'
    | '/dashboard'
    | '/docs'
    | '/keys'
    | '/login'
    | '/register'
    | '/api/public/check'
    | '/api/public/genqr'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app-password'
    | '/dashboard'
    | '/docs'
    | '/keys'
    | '/login'
    | '/register'
    | '/api/public/check'
    | '/api/public/genqr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppPasswordRoute: typeof AppPasswordRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  KeysRoute: typeof KeysRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicCheckRoute: typeof ApiPublicCheckRoute
  ApiPublicGenqrRoute: typeof ApiPublicGenqrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-password': {
      id: '/app-password'
      path: '/app-password'
      fullPath: '/app-password'
      preLoaderRoute: typeof AppPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/genqr': {
      id: '/api/public/genqr'
      path: '/api/public/genqr'
      fullPath: '/api/public/genqr'
      preLoaderRoute: typeof ApiPublicGenqrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check': {
      id: '/api/public/check'
      path: '/api/public/check'
      fullPath: '/api/public/check'
      preLoaderRoute: typeof ApiPublicCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppPasswordRoute: AppPasswordRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  KeysRoute: KeysRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicCheckRoute: ApiPublicCheckRoute,
  ApiPublicGenqrRoute: ApiPublicGenqrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
